/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Connection.ConnectionFactory;
import DAO.BarcoDAO;
import Entidades.Barco;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author juanc
 */
public class AgregarBarco extends javax.swing.JFrame {

    /**
     * Creates new form guardarBarco
     */
    public AgregarBarco(ConnectionFactory connection, BarcoDAO barcos) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.connection = connection;
        this.barcos = barcos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloAgregarBarco = new javax.swing.JLabel();
        labelNombreBarco = new javax.swing.JLabel();
        labelIdSocioBarco = new javax.swing.JLabel();
        labelAmarreBarco = new javax.swing.JLabel();
        labelCuotaBarco = new javax.swing.JLabel();
        areaCuotaBarco = new javax.swing.JTextField();
        areaNombreBarco = new javax.swing.JTextField();
        areaIdSocioBarco = new javax.swing.JTextField();
        areaAmarreBarco = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        guardarBarco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 450));
        getContentPane().setLayout(null);

        tituloAgregarBarco.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tituloAgregarBarco.setText("Agregar Barco");
        getContentPane().add(tituloAgregarBarco);
        tituloAgregarBarco.setBounds(180, 20, 240, 60);

        labelNombreBarco.setText("Nombre");
        getContentPane().add(labelNombreBarco);
        labelNombreBarco.setBounds(70, 110, 50, 16);

        labelIdSocioBarco.setText("Id Socio");
        getContentPane().add(labelIdSocioBarco);
        labelIdSocioBarco.setBounds(70, 160, 50, 16);

        labelAmarreBarco.setText("Amarre");
        getContentPane().add(labelAmarreBarco);
        labelAmarreBarco.setBounds(70, 210, 50, 16);

        labelCuotaBarco.setText("Cuota");
        getContentPane().add(labelCuotaBarco);
        labelCuotaBarco.setBounds(70, 260, 33, 16);
        getContentPane().add(areaCuotaBarco);
        areaCuotaBarco.setBounds(130, 260, 410, 22);
        getContentPane().add(areaNombreBarco);
        areaNombreBarco.setBounds(130, 110, 410, 22);
        getContentPane().add(areaIdSocioBarco);
        areaIdSocioBarco.setBounds(130, 160, 410, 22);
        getContentPane().add(areaAmarreBarco);
        areaAmarreBarco.setBounds(130, 210, 410, 22);

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(340, 350, 100, 25);

        guardarBarco.setText("Guardar");
        guardarBarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBarcoActionPerformed(evt);
            }
        });
        getContentPane().add(guardarBarco);
        guardarBarco.setBounds(160, 350, 79, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void guardarBarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBarcoActionPerformed
        Barco barcoNuevo = new Barco();
        barcoNuevo.setNombreBarco(areaNombreBarco.getText());
        barcoNuevo.setIdSocio(Integer.parseInt(areaIdSocioBarco.getText()));
        barcoNuevo.setNumAmarre(Integer.parseInt(areaAmarreBarco.getText()));
        barcoNuevo.setCuotaAmarre(Integer.parseInt(areaCuotaBarco.getText()));
        
        try {
            barcos.add(barcoNuevo);
        } catch (Exception ex) {
            Logger.getLogger(AgregarBarco.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ListaBarcos lb = new ListaBarcos(connection, barcos);
        lb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guardarBarcoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarBarco(connection, barcos).setVisible(true);
            }
        });
    }

    static ConnectionFactory connection;
    static BarcoDAO barcos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaAmarreBarco;
    private javax.swing.JTextField areaCuotaBarco;
    private javax.swing.JTextField areaIdSocioBarco;
    private javax.swing.JTextField areaNombreBarco;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton guardarBarco;
    private javax.swing.JLabel labelAmarreBarco;
    private javax.swing.JLabel labelCuotaBarco;
    private javax.swing.JLabel labelIdSocioBarco;
    private javax.swing.JLabel labelNombreBarco;
    private javax.swing.JLabel tituloAgregarBarco;
    // End of variables declaration//GEN-END:variables
}
