/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Connection.ConnectionFactory;
import DAO.SocioDAO;
import Entidades.Socio;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author juanc
 */
public class AgregarSocio extends javax.swing.JFrame {

    /**
     * Creates new form agregarSocio
     */
    public AgregarSocio(ConnectionFactory connection, SocioDAO socios) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.connection = connection;
        this.socios = socios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloAgregarSocio = new javax.swing.JLabel();
        labelNombreSocio = new javax.swing.JLabel();
        labelDireccionSocio = new javax.swing.JLabel();
        areaNombreSocio = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        guardarSocio = new javax.swing.JButton();
        areaDireccionSocio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 450));
        getContentPane().setLayout(null);

        tituloAgregarSocio.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tituloAgregarSocio.setText("Agregar Socio");
        getContentPane().add(tituloAgregarSocio);
        tituloAgregarSocio.setBounds(180, 20, 240, 60);

        labelNombreSocio.setText("Nombre");
        getContentPane().add(labelNombreSocio);
        labelNombreSocio.setBounds(50, 120, 50, 16);

        labelDireccionSocio.setText("Direccion");
        getContentPane().add(labelDireccionSocio);
        labelDireccionSocio.setBounds(50, 170, 60, 16);
        getContentPane().add(areaNombreSocio);
        areaNombreSocio.setBounds(110, 120, 440, 22);

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(350, 280, 100, 25);

        guardarSocio.setText("Guardar");
        guardarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarSocioActionPerformed(evt);
            }
        });
        getContentPane().add(guardarSocio);
        guardarSocio.setBounds(140, 280, 79, 25);
        getContentPane().add(areaDireccionSocio);
        areaDireccionSocio.setBounds(110, 170, 440, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void guardarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarSocioActionPerformed
        Socio socioNuevo = new Socio();
        socioNuevo.setNombre(areaNombreSocio.getText());
        socioNuevo.setDireccion(areaDireccionSocio.getText());

        
        try {        
            socios.add(socioNuevo);
        } catch (Exception ex) {
            Logger.getLogger(AgregarSocio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ListaSocios ls = new ListaSocios(connection, socios);
        ls.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guardarSocioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarSocio(connection, socios).setVisible(true);
            }
        });
    }

    static ConnectionFactory connection;
    static SocioDAO socios;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaDireccionSocio;
    private javax.swing.JTextField areaNombreSocio;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton guardarSocio;
    private javax.swing.JLabel labelDireccionSocio;
    private javax.swing.JLabel labelNombreSocio;
    private javax.swing.JLabel tituloAgregarSocio;
    // End of variables declaration//GEN-END:variables
}
