/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Connection.ConnectionFactory;
import DAO.SocioDAO;
import Entidades.Socio;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanc
 */
public class ListaSocios extends javax.swing.JFrame {

    /**
     * Creates new form ListaSocios
     */
    public ListaSocios(ConnectionFactory connection, SocioDAO socios) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        ListaSocios.connection = connection;
        ListaSocios.socios = socios;                       
        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulosSocios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSocios = new javax.swing.JTable();
        agregarSocio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 450));
        getContentPane().setLayout(null);

        titulosSocios.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titulosSocios.setText("Socios");
        getContentPane().add(titulosSocios);
        titulosSocios.setBounds(240, 10, 120, 60);

        tablaSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Socio", "Nombre", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSociosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSocios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 70, 620, 300);

        agregarSocio.setText("Agregar");
        agregarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarSocioActionPerformed(evt);
            }
        });
        getContentPane().add(agregarSocio);
        agregarSocio.setBounds(260, 380, 79, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarSocioActionPerformed
        AgregarSocio agregar = new AgregarSocio(connection, socios);
        agregar.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_agregarSocioActionPerformed

    private void tablaSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSociosMouseClicked
        DefaultTableModel model = (DefaultTableModel)tablaSocios.getModel();
        int selectedRow = tablaSocios.getSelectedRow();
        
        int id = (int) model.getValueAt(selectedRow, 0);
        try {            
            SocioModificar actualizar = new SocioModificar(id, connection, socios);
            actualizar.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ListaSocios.class.getName()).log(Level.SEVERE, null, ex);
        }
             
        this.dispose();
    }//GEN-LAST:event_tablaSociosMouseClicked
    
    private void cargar() {
        ArrayList<Socio> lista = new ArrayList<>();             
        
        try {
            lista = socios.getAll();
        } catch (Exception ex) {
            Logger.getLogger(ListaSocios.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        for(int i = 0; i< lista.size(); i++){
            Socio socio = lista.get(i);
            int id = socio.getId();
            String nombre = socio.getNombre();
            String direccion = socio.getDireccion();
            
            tablaSocios.setValueAt(id, i, 0);
            tablaSocios.setValueAt(nombre, i, 1);
            tablaSocios.setValueAt(direccion, i, 2);
            
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaSocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaSocios(connection, socios).setVisible(true);
            }
        });
    }
    
    static ConnectionFactory connection;
    static SocioDAO socios;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarSocio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSocios;
    private javax.swing.JLabel titulosSocios;
    // End of variables declaration//GEN-END:variables
}
