/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Connection.ConnectionFactory;
import DAO.SalidaDAO;
import DAO.SalidaDaoImp;
import Entidades.Salida;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author juanc
 */
public class ListaSalidas extends javax.swing.JFrame {

    /**
     * Creates new form ListaSalidas
     */
    public ListaSalidas(ConnectionFactory connection) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ListaSalidas.connection = connection; 
        salidas = new SalidaDaoImp(connection);
        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloSalidas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSalidas = new javax.swing.JTable();
        agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(620, 450));
        setMinimumSize(new java.awt.Dimension(620, 450));
        getContentPane().setLayout(null);

        tituloSalidas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tituloSalidas.setText("Salidas");
        getContentPane().add(tituloSalidas);
        tituloSalidas.setBounds(240, 10, 130, 60);

        tablaSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Barco", "Destino", "Fecha", "Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSalidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSalidasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSalidas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 70, 620, 300);

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar);
        agregar.setBounds(270, 380, 79, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaSalidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSalidasMouseClicked
//        DefaultTableModel model = (DefaultTableModel)tablaSalidas.getModel();
//        int selectedRow = tablaSalidas.getSelectedRow();
//
//        int id = (int) model.getValueAt(selectedRow, 0);
//        try {
//            BarcoModificar actualizar = new BarcoModificar(id, connection, barcos);
//            actualizar.setVisible(true);
//        } catch (Exception ex) {
//            Logger.getLogger(ListaSocios.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        this.dispose();
    }//GEN-LAST:event_tablaSalidasMouseClicked

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        AgregarSalida agregar = new AgregarSalida(connection, salidas);
        agregar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregarActionPerformed

    public void cargar(){
        ArrayList<Salida> lista = new ArrayList<>();             
        
        try {
            lista = (ArrayList<Salida>) salidas.getAll();
        } catch (Exception ex) {
            Logger.getLogger(ListaSocios.class.getName()).log(Level.SEVERE, null, ex);            
        }
                
        for(int i = 0; i< lista.size(); i++){
            Salida salida = lista.get(i);
            
            int idBarco = salida.getIdBarco();
            String destino = salida.getDestino();
            String fecha = salida.getFecha();
            int hora = salida.getHora();
            
            tablaSalidas.setValueAt(idBarco, i, 0);
            tablaSalidas.setValueAt(destino, i, 1);
            tablaSalidas.setValueAt(fecha, i, 2);          
            tablaSalidas.setValueAt(hora, i, 3);                        
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaSalidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaSalidas(connection).setVisible(true);
            }
        });
    }
    
    static ConnectionFactory connection;
    SalidaDAO salidas;    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSalidas;
    private javax.swing.JLabel tituloSalidas;
    // End of variables declaration//GEN-END:variables
}
