/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Connection.ConnectionFactory;
import Connection.MySQLConnectionFactory;
import DAO.BarcoDAO;
import DAO.BarcoDaoImp;
import DAO.SocioDAO;
import DAO.SocioDaoImp;

/**
 *
 * @author juanc
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSocios = new javax.swing.JButton();
        botonBarcos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 450));
        getContentPane().setLayout(null);

        botonSocios.setText("Socios");
        botonSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSociosActionPerformed(evt);
            }
        });
        getContentPane().add(botonSocios);
        botonSocios.setBounds(130, 180, 100, 50);

        botonBarcos.setText("Barcos");
        botonBarcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBarcosActionPerformed(evt);
            }
        });
        getContentPane().add(botonBarcos);
        botonBarcos.setBounds(360, 180, 100, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSociosActionPerformed
        ListaSocios ls = new ListaSocios(connection, socios);
        ls.setVisible(true);
    }//GEN-LAST:event_botonSociosActionPerformed

    private void botonBarcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBarcosActionPerformed
        ListaBarcos lb = new ListaBarcos(connection, barcos);
        lb.setVisible(true);
    }//GEN-LAST:event_botonBarcosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    ConnectionFactory connection = new MySQLConnectionFactory("localhost", "club_nautico", 3306, "root", "1234");
    SocioDAO socios = new SocioDaoImp(connection);
    BarcoDAO barcos = new BarcoDaoImp(connection);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBarcos;
    private javax.swing.JButton botonSocios;
    // End of variables declaration//GEN-END:variables
}
